---
sidebar: sidebar 
permalink: concept_before_you_begin_to_deploy_gfc.html 
keywords: global file cache, core, edge, management server 
summary: クラウドやリモートオフィスにグローバルファイルキャッシュを導入する前に、多くの要件について理解しておく必要があります。 
---
= グローバルファイルキャッシュの導入を開始する前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
クラウドやリモートオフィスにグローバルファイルキャッシュを導入する前に、多くの要件について理解しておく必要があります。



== グローバルファイルキャッシュコアの設計上の考慮事項

必要に応じて、グローバルファイルキャッシュファブリックを作成するために、 1 つまたは複数のグローバルファイルキャッシュコアインスタンスを配置する必要があります。Core インスタンスは、分散型グローバルファイルキャッシュエッジインスタンスとデータセンターファイルサーバリソース（ファイル共有、フォルダ、ファイルなど）間のトラフィックコープとして機能するように設計されています。

グローバルファイルキャッシュの展開を設計する際には、環境に適した規模、リソースの可用性、および冗長性を判断する必要があります。グローバルファイルキャッシュコアは、次の方法で展開できます。

* GFC コアスタンドアロンインスタンス
* GFC コア負荷分散設計（コールドスタンバイ）


を参照してください <<サイジングガイドライン>> Edge インスタンスの最大数と各構成でサポート可能な合計ユーザ数を理解するには、次の手順を実行します。

エンタープライズ環境に最適なオプションについては、グローバルファイルキャッシュソリューションエンジニアにお問い合わせください。



== サイジングガイドライン

初期システムを構成する際には、サイジングに関するいくつかのガイドラインについて留意する必要があります。システムを最適に使用するには、使用履歴が蓄積してからこれらの比率を再確認する必要があります。次のようなものがあり

* グローバルファイルキャッシュのエッジ / コア比
* 分散ユーザー数 / グローバルファイルキャッシュエッジ比率
* 分散ユーザー / グローバルファイルキャッシュコア比率




=== コアインスタンスごとのエッジインスタンスの数

このガイドラインでは、グローバルファイルキャッシュコアインスタンスごとに最大 10 個のエッジインスタンスを推奨しています。グローバルファイルキャッシュコアインスタンスごとに最大 20 個のエッジを使用します。これは、最も一般的なワークロードのタイプと平均ファイルサイズに大きく依存します。より一般的なワークロードでは、コアごとに Edge インスタンスを追加できますが、このような場合は、ファイルセットのタイプとサイズに応じて、 Edge インスタンスと Core インスタンスの数を適切にサイジングするためにネットアップサポートにお問い合わせください。


NOTE: 複数のグローバルファイルキャッシュエッジインスタンスとコアインスタンスを同時に利用して、要件に応じてインフラをスケールアウトできます。



=== Edge インスタンスごとの同時ユーザー数

Global File Cache Edge では、キャッシュアルゴリズムとファイルレベルの差分データの処理が大幅に増加しています。1 つのグローバルファイルキャッシュエッジインスタンスは、専用の物理エッジインスタンスあたり最大 400 ユーザー、専用の仮想環境に最大 200 ユーザーを提供できます。これは、最も一般的なワークロードのタイプと平均ファイルサイズに大きく依存します。より大規模なコラボレーションファイルタイプの場合は、 Global File Cache Edge ごとの最大ユーザー数の 50% を目安にしてください（物理環境または仮想環境によって異なります）。平均ファイルサイズが 1MB 未満の一般的な Office アイテムの場合は、 Global File Cache Edge ごとに 100% ユーザーの上限に向かってガイドします（物理環境または仮想環境によって異なります）。


NOTE: Global File Cache Edge は、仮想インスタンスまたは物理インスタンス上で実行されているかどうかを検出し、ローカル仮想ファイル共有への SMB 接続の数を最大 200 または 400 の同時接続に制限します。



=== コアインスタンスあたりの同時ユーザー数

Global File Cache Core インスタンスは非常にスケーラブルで、 Core あたり 3,000 ユーザの同時ユーザ数を推奨します。これは、最も一般的なワークロードのタイプと平均ファイルサイズに大きく依存します。

エンタープライズ環境に最適なオプションについては、グローバルファイルキャッシュソリューションエンジニアにお問い合わせください。



== 前提条件

このセクションで説明する前提条件は、クラウドにインストールされているコンポーネント（ Global File Cache Management Server および Global File Cache Core ）を対象としています。

グローバルファイルキャッシュエッジの前提条件について説明します link:download_gfc_resources.html#global-file-cache-edge-requirements["こちらをご覧ください"]。



=== Cloud Manager インスタンス

Cloud Volumes ONTAP for Azure をストレージプラットフォームとして使用している場合は、最新のものに示す権限が Cloud Manager に割り当てられていることを確認してください https://occm-sample-policies.s3.amazonaws.com/Policy_for_cloud_Manager_Azure_3.8.7.json["Azure 向け Cloud Manager ポリシー"^]。

新しく作成したインスタンスには、デフォルトで必要なすべての権限が付与されます。バージョン 3.8.7 （ 2020 年 8 月 3 日）より前のバージョンでインスタンスを導入している場合は、これらの項目を追加する必要があります。

[source, json]
----
"Microsoft.Resources/deployments/operationStatuses/read",
"Microsoft.Insights/Metrics/Read",
"Microsoft.Compute/virtualMachines/extensions/write",
"Microsoft.Compute/virtualMachines/extensions/read",
"Microsoft.Compute/virtualMachines/extensions/delete",
"Microsoft.Compute/virtualMachines/delete",
"Microsoft.Network/networkInterfaces/delete",
"Microsoft.Network/networkSecurityGroups/delete",
"Microsoft.Resources/deployments/delete",
----


=== ストレージプラットフォーム（ボリューム）

バックエンドストレージプラットフォームは、この場合、導入した Cloud Volumes ONTAP インスタンスで SMB ファイル共有を提供します。グローバルファイルキャッシュを通じて公開される共有では、 NTFS 権限によるアクセス権の制限を行いながら、 Everyone グループに共有レベルのフルコントロールを許可する必要があります。

Cloud Volumes ONTAP インスタンスで SMB ファイル共有をセットアップしていない場合は、インストール時に設定できるように次の情報を用意しておく必要があります。

* Active Directory ドメイン名、ネームサーバの IP アドレス、 Active Directory 管理者のクレデンシャル。
* 作成するボリュームの名前とサイズ、ボリュームを作成するアグリゲートの名前、および共有名。


ボリュームは、アプリケーション用のデータセットの合計数に対応できるだけの大きさであり、データセットの拡張に合わせて拡張できることを推奨します。作業環境に複数のアグリゲートがある場合は、を参照してください link:task_managing_storage.html["既存のアグリゲートの管理"^] をクリックして、新しいボリュームの空きスペースが最も多いアグリゲートを確認します。



=== グローバルファイルキャッシュ管理サーバ

このグローバルファイルキャッシュ管理サーバでは、クラウドプロバイダサブスクリプションサービスに接続して次の URL にアクセスするために、 HTTPS （ TCP ポート 443 ）経由の外部アクセスが必要です。

* https://talonazuremicroservices.azurewebsites.net["https://talonazuremicroservices.azurewebsites.net"]
* https://talonlicensing.table.core.windows.net["https://talonlicensing.table.core.windows.net"]


Global File Cache ソフトウェアが正常に動作するためには、 WAN 最適化デバイスまたはファイアウォール制限ポリシーからこのポートを除外する必要があります。

グローバルファイルキャッシュ管理サーバーには、インスタンスの一意な ( 地理的な ) NetBIOS 名 (GFC-MS1 など ) も必要です。


NOTE: 1 つの管理サーバで、異なる作業環境に配置された複数のグローバルファイルキャッシュコアインスタンスをサポートできます。Cloud Manager から導入した場合、それぞれの作業環境に専用のバックエンドストレージがあるため、同じデータを格納することはできません。



=== グローバルファイルキャッシュコア

このグローバルファイルキャッシュコアは、 TCP ポート範囲 6618-6630 でリッスンします。ファイアウォールまたはネットワークセキュリティグループ（ NSG ）の設定によっては、インバウンドポートルールを使用してこれらのポートへのアクセスを明示的に許可する必要があります。また、 Global File Cache ソフトウェアが正常に動作するためには、 WAN 最適化デバイスまたはファイアウォール制限ポリシーからこれらのポートを除外する必要があります。

グローバルファイルキャッシュコアの要件は次のとおりです。

* インスタンスの一意な（地理的な） NetBIOS 名 （ GFC-CORE1 など）
* Active Directory ドメイン名
+
** グローバルファイルキャッシュインスタンスが Active Directory ドメインに参加している必要があります。
** グローバルファイルキャッシュインスタンスは、グローバルファイルキャッシュ固有の組織単位（ OU ）で管理し、継承された会社の GPO から除外する必要があります。


* サービスアカウント：このグローバルファイルキャッシュコアのサービスは、特定のドメインユーザーアカウントとして実行されます。このアカウント（サービスアカウントとも呼ばれます）には、グローバルファイルキャッシュコアインスタンスに関連付けられる各 SMB サーバーに対して次の権限が必要です。
+
** プロビジョニングされたサービスアカウントはドメインユーザである必要があります。




ネットワーク環境における制限のレベルおよび GPO によっては、このアカウントにドメイン管理者権限が必要になる場合があります。

* Run As a Service 権限が必要です。
* パスワードは「無期限」に設定する必要があります。
* アカウントオプションの [ 次回ログオン時にパスワードを変更する必要があります ] を無効にします ( オフ ) 。
* この機能は、バックエンドファイルサーバの組み込みの Backup Operators グループのメンバーである必要があります（ Cloud Manager から導入すると自動的に有効になります）。




=== License Management Server の略

* グローバルファイルキャッシュライセンス管理サーバ（ LMS ）は、 Microsoft Windows Server 2016 Standard エディションまたは Datacenter エディション、または Windows Server 2019 Standard エディションまたは Datacenter エディション（できればデータセンターまたはクラウドのグローバルファイルキャッシュコアインスタンス上）で設定する必要があります。
* 別個の Global File Cache LMS インスタンスが必要な場合は、最新の Global File Cache ソフトウェアインストールパッケージを初期状態の Microsoft Windows Server インスタンスにインストールする必要があります。
* LMS インスタンスは、 HTTPS （ TCP ポート 443 ）を使用してサブスクリプションサービス（ Azure Services/public internet ）に接続できる必要があります。
* コアインスタンスとエッジインスタンスは、 HTTPS （ TCP ポート 443 ）を使用して LMS インスタンスに接続する必要があります。




=== ネットワーキング

* ファイアウォール：グローバルファイルキャッシュエッジインスタンスとコアインスタンスの間で TCP ポートを許可する必要があります。
* グローバルファイルキャッシュ TCP ポート： 443 （ HTTPS ）、 6618 – 6630 。
* ネットワーク最適化デバイス（ Riverbed Steelhead など）は、グローバルファイルキャッシュ固有のポート（ TCP 6618-6630 ）をパススルーするように構成する必要があります。

