---
sidebar: sidebar 
permalink: concept_storage_management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode 
summary: Cloud Manager は、 Cloud Volumes ONTAP ストレージの簡易化された高度な管理機能を提供します。 
---
= ストレージ管理
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager は、 Cloud Volumes ONTAP ストレージの簡易化された高度な管理機能を提供します。


IMPORTANT: すべてのディスクとアグリゲートは、 Cloud Manager から直接作成および削除する必要があります。これらのアクションは、別の管理ツールから実行しないでください。これにより、システムの安定性が低下し、将来ディスクを追加できなくなる可能性があります。また、クラウドプロバイダの冗長料金が発生する可能性もあります。



== ストレージのプロビジョニング

Cloud Manager では、ディスクを購入してアグリゲートを管理することで、 Cloud Volumes ONTAP のストレージプロビジョニングが容易になります。ボリュームを作成するだけで済みます。必要に応じて、 Advanced Allocation オプションを使用してアグリゲートをプロビジョニングできます。



=== プロビジョニングの簡素化

アグリゲートは、ボリュームにクラウドストレージを提供します。Cloud Manager では、インスタンスを起動したとき、および追加ボリュームをプロビジョニングしたときに、アグリゲートが作成されます。

ボリュームを作成すると、 Cloud Manager は次の 3 つのいずれかを実行します。

* 十分な空きスペースがある既存のアグリゲートにボリュームを配置します。
* ボリュームを既存のアグリゲートに配置するには、そのアグリゲート用に追加のディスクを購入します。
* 新しいアグリゲートのディスクを購入し、そのアグリゲートにボリュームを配置します。


Cloud Manager は、アグリゲートの最大サイズ、シンプロビジョニングが有効になっているかどうか、アグリゲートの空きスペースのしきい値など、いくつかの要因を確認して新しいボリュームをどこに配置するかを決定します。


TIP: アカウント管理者は、 [ 設定 *] ページから空き容量のしきい値を変更できます。



==== AWS でのアグリゲートのディスクサイズの選択

Cloud Manager は、 AWS で Cloud Volumes ONTAP 用の新しいアグリゲートを作成すると、システム内のアグリゲートの数が増えるにつれて、アグリゲート内のディスクサイズを徐々に増加させます。Cloud Manager は、 AWS で許可される最大データディスク数に達する前に、システムの最大容量を利用できるようにします。

たとえば、 Cloud Manager では、 Cloud Volumes ONTAP Premium または BYOL システムのアグリゲートに次のディスクサイズを選択できます。

[cols="3*"]
|===
| アグリゲート番号 | ディスクサイズ | 最大アグリゲート容量 


| 1. | 500 MB | 3 TB 


| 4. | 1 TB | 6TB 


| 6. | 2TB | 12TB 
|===
ディスクサイズは、 Advanced Allocation オプションを使用して選択できます。



=== 高度な割り当て

Cloud Manager でアグリゲートを管理するのではなく、自分で管理できます。 link:task_provisioning_storage.html#creating-aggregates["Advanced allocation * ページからアクセスします"]では、特定の数のディスクを含む新しいアグリゲートの作成、既存のアグリゲートへのディスクの追加、および特定のアグリゲートでのボリュームの作成を行うことができます。



== 容量管理

アカウント管理者は、ストレージ容量の決定について Cloud Manager から通知するかどうか、または Cloud Manager が容量の要件を自動的に管理するかどうかを選択できます。これらのモードの仕組みを理解するのに役立つ場合があります。



=== 自動容量管理

容量管理モードは、デフォルトで自動に設定されています。このモードでは、 Cloud Volumes ONTAP インスタンスで追加の容量が必要になると、 Cloud Manager によって新しいディスクが自動的に購入されます。また、未使用のディスクセット（アグリゲート）の削除、必要に応じてアグリゲート間でのボリュームの移動、ディスクの障害状態の解除を試行します。

次の例は、このモードの動作を示しています。

* EBS ディスクが 5 台以下のアグリゲートが容量のしきい値に達すると、 Cloud Manager はそのアグリゲートの新しいディスクを自動的に購入し、ボリュームを継続して拡張できるようにします。
* 12 個の Azure ディスクを持つアグリゲートが容量のしきい値に達すると、 Cloud Manager は、ボリュームをそのアグリゲートから使用可能な容量を持つアグリゲートまたは新しいアグリゲートに自動的に移動します。
+
ボリュームに新しいアグリゲートを作成すると、 Cloud Manager はそのボリュームのサイズに対応するディスクサイズを選択します。

+
元のアグリゲートに空きスペースがあることに注意してください。既存のボリュームまたは新しいボリュームでは、そのスペースを使用できます。このシナリオでは、 AWS 、 Azure 、 GCP にスペースを戻すことはできません。

* アグリゲートに 12 時間を超えるボリュームが含まれていない場合は、 Cloud Manager によって削除されます。




==== 容量の自動管理による LUN の管理

Cloud Manager の自動容量管理は、 LUN には適用されません。Cloud Manager で LUN を作成すると自動拡張機能が無効になります。



==== 容量の自動管理による inode の管理

Cloud Manager は、ボリューム上の inode の使用量を監視します。inode の 85% を使用すると、 Cloud Manager はボリュームのサイズを増やして、使用可能な inode の数を増やします。ボリュームに含めることができるファイル数は、ボリューム内の inode の数によって決まります。



=== 手動による容量管理

アカウント管理者が容量管理モードを手動に設定した場合、容量の決定が必要な状況になると、 Cloud Manager に「 Action Required 」メッセージが表示され、自動モードで説明されている例と同じ例が手動モードにも適用されますが、アクションを受け入れる必要があります。
