---
sidebar: sidebar 
permalink: concept_backup_to_cloud.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, back up volumes, Backup to Cloud, restore volumes, billing, cost, on-premises ONTAP, onprem 
summary: クラウドへのバックアップは、 ONTAP クラスタとオンプレミス Cloud Volumes ONTAP クラスタに対応するアドオンサービスで、保護のためのバックアップとリストア機能を提供し、クラウドデータを長期にわたってアーカイブできる。バックアップは、短期リカバリやクローニングに使用されるボリューム Snapshot コピーとは無関係に、クラウドアカウントのオブジェクトストアに格納されます。 
---
= クラウドへのバックアップの詳細をご確認ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
クラウドへのバックアップは、 ONTAP クラスタとオンプレミス Cloud Volumes ONTAP クラスタに対応するアドオンサービスで、保護のためのバックアップとリストア機能を提供し、クラウドデータを長期にわたってアーカイブできる。バックアップは、短期リカバリやクローニングに使用されるボリューム Snapshot コピーとは無関係に、クラウドアカウントのオブジェクトストアに格納されます。

クラウドへのバックアップには、が採用されています https://cloud.netapp.com/cloud-backup-service["Cloud Backup サービスの略"^]。


NOTE: すべてのバックアップ処理とリストア処理には、 Cloud Manager を使用する必要があります。ONTAP から直接、またはクラウドプロバイダから何らかの操作を実行すると、サポートされない構成になります。



== の機能

* データボリュームの独立したコピーをクラウド上の低コストのオブジェクトストレージにバックアップできます。
* バックアップデータは、転送中の AES-256 ビット暗号化と TLS 1.2 HTTPS 接続によって保護されます。
* クラウドからクラウドへ、オンプレミスの ONTAP システムからクラウドへバックアップできます。
* 単一ボリュームで最大 1 、 019 個のバックアップをサポート
* 特定の時点からデータをリストアします。
* ソースシステム上のボリュームまたは別のシステムにデータをリストアします。




== サポートされている作業環境とオブジェクトストレージプロバイダ

クラウドへのバックアップは、次のタイプの作業環境でサポートされています。

* AWS の Cloud Volumes ONTAP
* Azure の Cloud Volumes ONTAP
* オンプレミスの ONTAP クラスタ




== コスト

クラウドへのバックアップには、お客様所有のライセンスを使用（ BYOL ）と従量課金制（ PAYGO ）の 2 つの料金プランがあります。

BYOL の場合、ネットアップに料金を支払うことで、このサービスを一定期間利用できます。たとえば 6 カ月とし、最大バックアップ容量である 10GB （ストレージ効率化前）と言います。そのため、オブジェクトストレージのコストについてクラウドプロバイダに支払う必要があります。このサービスを有効にするために、 Cloud Manager のライセンスページに入力するシリアル番号が表示されます。いずれかの制限に達すると、ライセンスを更新する必要があります。を参照してください link:task_managing_licenses.html#adding-and-updating-your-backup-byol-license["バックアップ BYOL ライセンスを追加および更新する"^]。Backup BYOL ライセンス環境は、に関連付けられているすべての Cloud Volumes ONTAP システムをライセンスしたものです link:concept_cloud_central_accounts.html["Cloud Central アカウント"^]。

PAYGO の場合は、オブジェクトストレージのコストについてクラウドプロバイダに支払い、バックアップライセンスのコストについてはネットアップに支払う必要があります。ライセンスコストは、使用済み容量（ストレージ効率化前）に基づいて計算されます。

* AWS https://aws.amazon.com/marketplace/pp/B07QX2QLXX["価格の詳細については、 Cloud Manager Marketplace のサービスを参照してください"^]。
* Azure https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview["価格の詳細については、 Cloud Manager Marketplace のサービスを参照してください"^]。




=== 無償トライアルをご利用ください

30 日間の無償トライアルをご利用いただけます。試用版を使用すると、残っている無料試用日数が通知されます。無償トライアルが終了すると、バックアップは作成されなくなります。サービスを引き続き使用するには、サービスに登録するかライセンスを購入する必要があります。

サービスが無効になってもバックアップは削除されません。バックアップを削除しないかぎり、バックアップで使用する容量のオブジェクトストレージのコストは引き続きクラウドプロバイダから請求されます。



== クラウドへのバックアップの仕組み

Cloud Volumes ONTAP またはオンプレミスの ONTAP システムでクラウドへのバックアップを有効にすると、サービスはデータのフルバックアップを実行します。ボリューム Snapshot はバックアップイメージに含まれません。初期バックアップ後は、追加のバックアップはすべて差分になります。つまり、変更されたブロックと新しいブロックのみがバックアップされます。



=== バックアップの保管場所バックアップノバショ

バックアップコピーは、 Cloud Manager がクラウドアカウントに作成する S3 バケットまたは Azure BLOB コンテナに格納されます。Cloud Volumes ONTAP システムの場合、オブジェクトストアは Cloud Volumes ONTAP システムと同じリージョンに作成されます。オンプレミスの ONTAP システムでは、サービスを有効にするときにリージョンを指定します。

Cloud Volumes ONTAP システムまたはオンプレミスの ONTAP システムごとに 1 つのオブジェクトストアがあります。Cloud Manager は、次のようにオブジェクトストア名を指定します。 NetApp-backup- _clusteruuid_

このオブジェクトストアは削除しないでください。

注：

* AWS では、 Cloud Manager によってが有効になります https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html["Amazon S3 ブロックのパブリックアクセス機能"^] を S3 バケットに配置します。
* Azure では、 Cloud Manager は BLOB コンテナのストレージアカウントを持つ新規または既存のリソースグループを使用します。




=== サポートされている S3 ストレージクラス

Amazon S3 では、バックアップは _Standard_storage クラスから開始し、 30 日後に _Standard-Infrequent Access_storage クラスに移行します。



=== サポートされる Azure Blob アクセス階層

Azure では、各バックアップは _COT_ACCESS 階層に関連付けられています。



=== バックアップ設定はシステム全体に適用されます

クラウドへのバックアップを有効にすると、システムで指定したすべてのボリュームがクラウドにバックアップされます。

保持するバックアップのスケジュールと数はシステムレベルで定義されます。バックアップ設定は、システム上のすべてのボリュームに適用されます。



=== スケジュールは、 daily 、 weekly 、 monthly 、またはその組み合わせです

すべてのボリュームについて、日単位、週単位、または月単位のバックアップを選択できます。また、システム定義のポリシーの中から、 3 カ月、 1 年、 7 年のバックアップと保持を提供するポリシーを選択することもできます。ポリシーは次のとおりです。

[cols="30,20,20,20,30"]
|===
| ポリシー名 3+| 間隔ごとのバックアップ ... | 最大バックアップ 


|  | * 毎日 * | * 毎週 * | * 毎月 * |  


| Netapp3MonthsRetention | 30 | 13 | 3. | 46 


| Netapp1YearRetention | 30 | 13 | 12. | 55 


| ネッパ7YearsRetention | 30 | 53 | 84 | 167 
|===
カテゴリまたは間隔のバックアップの最大数に達すると、古いバックアップは削除されるため、常に最新のバックアップが保持されます。

データ保護ボリュームのバックアップの保持期間は、ソースの SnapMirror 関係の定義と同じになります。API を使用して必要に応じてこの値を変更できます。



=== バックアップは午前 0 時に作成されます

* 日次バックアップは、毎日午前 0 時を過ぎた直後に開始されます。
* 週次バックアップは、日曜日の朝の午前 0 時を過ぎた直後に開始されます
* 月単位のバックアップは、毎月 1 日の午前 0 時を過ぎた直後に開始されます。


この時点では、ユーザーが指定した時刻にバックアップ操作をスケジュールすることはできません。



=== バックアップコピーは Cloud Central アカウントに関連付けられます

バックアップコピーはに関連付けられます link:concept_cloud_central_accounts.html["Cloud Central アカウント"^] Cloud Manager が配置されます。

同じ Cloud Central アカウントに複数の Cloud Manager システムがある場合、各 Cloud Manager システムには同じバックアップのリストが表示されます。これには、他の Cloud Manager システムの Cloud Volumes ONTAP インスタンスとオンプレミス ONTAP インスタンスに関連付けられたバックアップが含まれます。



=== BYOL ライセンスに関する考慮事項

Backup to Cloud BYOL ライセンスを使用している場合、 Cloud Manager は、バックアップが容量の上限に近づいたときやライセンスの有効期限に近づいたときに通知します。次の通知が表示されます。

* バックアップがライセンスで許可された容量の 80% に達したとき、および制限に達したときに再度実行されます
* ライセンスの有効期限が切れる 30 日前と、ライセンスの有効期限が切れたあとに再度有効になります


これらの通知を受け取った場合は、 Cloud Manager インターフェイスの右下にあるチャットアイコンを使用してライセンスを更新してください。

ライセンスの有効期限が切れると、次の 2 つのことが起こります。

* ONTAP システムに使用しているアカウントにマーケットプレイスアカウントがある場合、バックアップサービスは引き続き実行されますが、 PAYGO ライセンスモデルに切り替えられます。バックアップに使用する容量のバックアップライセンスのコストについては、クラウドプロバイダに課金されます。バックアップに必要なストレージコストについては、ネットアップにお問い合わせください。
* ONTAP システムに使用しているアカウントに Marketplace アカウントがない場合、バックアップサービスは引き続き実行されますが、有効期限に関するメッセージは引き続き送信されます。


BYOL サブスクリプションを更新すると、 Cloud Manager は NetApp から新しいライセンスを自動的に取得してインストールします。Cloud Manager がセキュアなインターネット接続経由でライセンスファイルにアクセスできない場合は、ユーザがファイルを取得して、 Cloud Manager に手動でアップロードできます。手順については、を参照してください link:task_managing_licenses.html#adding-and-updating-your-backup-byol-license["バックアップ BYOL ライセンスを追加および更新する"^]。

PAYGO ライセンスに切り替えられたシステムは、自動的に BYOL ライセンスに戻されます。また、ライセンスなしで実行されていたシステムは警告メッセージの受信を停止し、ライセンスの有効期限が切れている間に実行されたバックアップに対して課金されます。



== サポートされるボリューム

Backup to Cloud は、読み書き可能ボリュームとデータ保護（ DP ）ボリュームをサポートしています。

FlexGroup ボリュームは現在サポートされていません。



== 制限

* クラウドへのバックアップが有効になっている場合、 Cloud Volumes ONTAP またはオンプレミスのシステムでは WORM ストレージ（ SnapLock ）はサポートされません。
* オンプレミスの ONTAP システムからバックアップを作成する際のクラウドへのバックアップの制限事項：
+
** オンプレミスクラスタで ONTAP 9.7P5 以降が実行されている必要があります。
** Cloud Manager が Azure に導入されていること。オンプレミスの Cloud Manager 環境はサポートされていません。
** バックアップのデスティネーションの場所は、 Azure 上のオブジェクトストレージのみです。
** バックアップは、 Azure に導入されている Cloud Volumes ONTAP システムにのみリストアできます。オンプレミスの ONTAP システムや、別のクラウドプロバイダを使用している Cloud Volumes ONTAP システムにバックアップをリストアすることはできません。


* DP ボリュームをバックアップする場合は、ソースボリュームの SnapMirror ポリシーに定義されたルールで、「毎日」、「毎週」、または「毎月」の「クラウドへのバックアップ」ポリシー名に一致するラベルを使用する必要があります。そうしないと、その DP ボリュームのバックアップは失敗します。
* Azure では、 Cloud Volumes ONTAP の導入時にクラウドへのバックアップを有効にした場合、 Cloud Manager によってリソースグループが作成されます。このリソースグループは変更できません。クラウドへのバックアップを有効にする際に独自のリソースグループを選択する場合は、 Cloud Volumes ONTAP を導入する際に * クラウドへのバックアップを無効にしてから、クラウドへのバックアップを有効にして、クラウドへのバックアップ設定ページからリソースグループを選択します。
* Cloud Volumes ONTAP システムからボリュームをバックアップする場合、 Cloud Manager 以外で作成したボリュームは自動ではバックアップされません。
+
たとえば、 ONTAP CLI 、 ONTAP API 、または System Manager からボリュームを作成した場合、そのボリュームは自動的にはバックアップされません。

+
これらのボリュームをバックアップするには、クラウドへのバックアップを無効にしてから再度有効にする必要があります。


