---
sidebar: sidebar 
permalink: download_gfc_resources.html 
keywords: global file cache, edge 
summary: グローバルファイルキャッシュエッジソフトウェアをリモートオフィスにインストールする前に、多くの要件について理解しておく必要があります。 
---
= グローバルファイルキャッシュエッジインスタンスの展開を開始する前に
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
グローバルファイルキャッシュエッジソフトウェアをリモートオフィスにインストールする前に、多くの要件について理解しておく必要があります。



== 必要なリソースをダウンロード

ブランチオフィスで使用するグローバルファイルキャッシュ仮想テンプレート、ソフトウェアインストールパッケージ、およびその他の参照ドキュメントをダウンロードします。

* Windows Server 2016 仮想テンプレート：
+
https://repo.cloudsync.netapp.com/gfc/2K16_GFC_1_0_18_OVF.zip["NetApp GFC を含む Windows Server * 2016.OVA （ VMware vSphere 6.5 以降）"^]


* Windows Server 2019 仮想テンプレート：
+
https://repo.cloudsync.netapp.com/gfc/2K19_GFC_1_0_18_OVF.zip["Windows Server 206.OVA （ NetApp GFC を含む）（ VMware vSphere 6.5 以降）"^]


* グローバルファイルキャッシュエッジソフトウェア：
+
https://repo.cloudsync.netapp.com/gfc/GFC-1-0-0-21-Release.exe["NetApp GFC ソフトウェア（ .EXE ）"^]

* グローバルファイルキャッシュのドキュメント：
+
link:https://repo.cloudsync.netapp.com/gfc/NetApp%20GFC%20-%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]





== グローバルファイルキャッシュエッジの設計と導入

要件によっては、ブランチオフィスでの同時ユーザーセッションに基づいて、 1 つまたは複数のグローバルファイルキャッシュエッジインスタンスを配置する必要があります。Edge インスタンスは、ブランチオフィス内のエンドユーザに仮想ファイル共有を提供します。これは、関連付けられた Global File Cache Core インスタンスから透過的に拡張されています。グローバルファイルキャッシュエッジには、ブランチオフィス内のキャッシュされたファイルを含む「 d:\`NTFS ボリューム」が含まれている必要があります。


NOTE: グローバルファイルキャッシュエッジについては、を理解することが重要です link:concept_before_you_begin_to_deploy_gfc.html#sizing-guidelines["サイジングガイドライン"^]。これは、グローバルファイルキャッシュの配置に適した設計を行うのに役立ちます。また、拡張性、リソースの可用性、および冗長性の観点から、環境に最適なものを決定する必要があります。



=== グローバルファイルキャッシュエッジインスタンス

グローバルファイルキャッシュエッジインスタンスを導入する場合は、 Windows Server 2016 Standard Edition または Datacenter Edition 、または Windows Server 2019 Standard Edition または Datacenter Edition を導入するか、 Global File Cache の .OVA または「 .vhd 」テンプレートを使用して、単一の VM をプロビジョニングする必要があります。 これには、 Windows Server オペレーティングシステム（任意選択）およびグローバルファイルキャッシュソフトウェアが含まれます。



==== クイックステップ

. グローバルファイルキャッシュ仮想テンプレート、 Windows Server 2016 VM 、または Windows Server 2019 Standard エディションまたは Datacenter エディションを導入します。
. VM がネットワークに接続され、ドメインに参加し、 RDP を介してアクセス可能であることを確認します。
. 最新のグローバルファイルキャッシュエッジソフトウェアをインストールします。
. Global File Cache Management Server および Core インスタンスを特定します。
. グローバルファイルキャッシュエッジインスタンスを構成します。




== グローバルファイルキャッシュエッジの要件

Global File Cache Edge は、 Windows Server 2016 および 2019 をサポートするすべてのプラットフォームで機能するように設計されており、企業のリモートオフィスなどに IT を簡易化できます。さらに、グローバルファイルキャッシュは、既存のハードウェアインフラストラクチャ、仮想化、ハイブリッド / パブリッククラウド環境に導入できます。ほとんどの場合、基本レベルの要件を満たすことができます。

Global File Cache Edge が最適に機能するには、次のハードウェアおよびソフトウェアリソースが必要です。全体的なサイジングガイドラインの詳細については、を参照してください link:concept_before_you_begin_to_deploy_gfc.html#sizing-guidelines["サイジングガイドライン"]。



=== 強化されたサーバーアプライアンス

グローバルファイルキャッシュインストールパッケージを使用すると、任意の Microsoft Windows Server インスタンス上に強化されたソフトウェアアプライアンスが作成されます。_ グローバルファイルキャッシュパッケージをアンインストールしないでください。グローバルファイルキャッシュをアンインストールすると、サーバーインスタンスの機能に影響が及び、サーバーインスタンスの完全な再構築が必要になる場合があります。



=== 物理ハードウェアの要件

* 最低 4 個の CPU コア
* 16GB 以上の RAM
* 専用のシングルまたは冗長 1 Gbps NIC
* 10K RPM SAS HDD または SSD （推奨）
* ライトバックキャッシュ機能が有効になっている RAID コントローラ




=== 仮想導入の要件

ハイパーバイザープラットフォームは、ストレージサブシステムの観点からはパフォーマンス低下の影響を受けることがわかっています（レイテンシなど）。グローバルファイルキャッシュを使用してパフォーマンスを最適化するには、 SSD を搭載した物理サーバインスタンスを推奨します。

仮想環境で最大限のパフォーマンスを実現するには、物理ホストの要件に加えて、次の要件とリソースリザベーションを満たす必要があります。

Microsoft Hyper-V 2012 R2 以降：

* プロセッサ（ CPU ）： CPU は「 * 静的 * ：最小： 4 vCPU コア」として設定する必要があります。
* メモリ（ RAM ）：最小： 16 GB を * 静的 * として設定。
* ハードディスクのプロビジョニング：ハードディスクは * 固定ディスク * として構成する必要があります。


VMware vSphere 6.x 以降：

* プロセッサ（ CPU ）： CPU サイクルの予約を設定する必要があります。最小構成： 4 個の vCPU コア、 10 、 000 MHz
* メモリ（ RAM ）：最小： 16GB の予約。
* ハードディスクのプロビジョニング：
+
** ディスクプロビジョニングは「 * Thick provisioned Eager Zeroed * 」として設定する必要があります。
** ハードディスク共有は「 * 高」に設定する必要があります。
** Microsoft Windows でグローバルファイルキャッシュドライブがリムーバブルとして表示されないようにするには、 vSphere Client を使用して devicing.hotplug を * False * に設定する必要があります。


* ネットワーク：ネットワークインターフェイスは *VMXNET3* に設定する必要があります（ VM Tools が必要です）。


グローバルファイルキャッシュは Windows Server 2016 および 2019 で動作するため、仮想化プラットフォームではオペレーティングシステムをサポートする必要があります。また、 VM のゲストオペレーティングシステムのパフォーマンスを向上させ、 VM Tools などの VM の管理を行うユーティリティと統合する必要があります。



=== パーティションのサイジング要件

* C ： \- 最小 250GB （システム / ブートボリューム）
* D ： \ - 最小 1TB （グローバル・ファイル・キャッシュ・インテリジェント・ファイル・キャッシュ用の個別データ・ボリューム * ）


* 最小サイズは、アクティブデータセットの 2 倍です。キャッシュボリューム（ D ： \ ）は拡張が可能で、 Microsoft Windows NTFS ファイルシステムの制限によってのみ制限されます。



=== グローバルファイルキャッシュインテリジェントファイルキャッシュのディスク要件

グローバルファイルキャッシュインテリジェントファイルキャッシュディスク（ D ： \ ）のディスクレイテンシは、同時ユーザーあたり 0.5 ミリ秒未満の平均 I/O ディスクレイテンシと 1 MiBps のスループットを実現する必要があります。

詳細については、を参照してください link:https://repo.cloudsync.netapp.com/gfc/NetApp%20GFC%20-%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]。



=== ネットワーキング

* ファイアウォール：グローバルファイルキャッシュエッジと管理サーバとコアインスタンスの間で TCP ポートを許可する必要があります。
+
グローバルファイルキャッシュ TCP ポート： 443 （ HTTPS-LMS ）、 6618 ～ 6630 。

* ネットワーク最適化デバイス（ Riverbed Steelhead など）は、グローバルファイルキャッシュ固有のポート（ TCP 6618-6630 ）をパススルーするように構成する必要があります。




=== クライアントワークステーションとアプリケーションのベストプラクティス

Global File Cache は、お客様の環境に透過的に統合されるため、ユーザは、クライアントワークステーションを使用して、エンタープライズアプリケーションを実行しながら、集中管理されたデータにアクセスできます。グローバルファイルキャッシュを使用すると、データには直接ドライブマッピングまたは DFS 名前空間を介してアクセスできます。グローバルファイルキャッシュファブリック、インテリジェントファイルキャッシング、およびソフトウェアの主な側面の詳細については、を参照してください link:concept_before_you_begin_to_deploy_gfc.html["グローバルファイルキャッシュの展開を開始する前に"^] セクション。

最適なエクスペリエンスとパフォーマンスを確保するには、『グローバルファイルキャッシュユーザーガイド』に記載されている Microsoft Windows クライアントの要件およびベストプラクティスに準拠することが重要です。これは、すべてのバージョンの Microsoft Windows に適用されます。

詳細については、を参照してください link:https://repo.cloudsync.netapp.com/gfc/NetApp%20GFC%20-%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]。



=== ファイアウォールとアンチウイルスのベストプラクティス

グローバルファイルキャッシュは、最も一般的なウィルス対策アプリケーションスイートがグローバルファイルキャッシュと互換性があるかどうかを検証するために相応の努力を払いますが、ネットアップでは、これらのプログラムや関連する更新、サービスパック、変更によって発生する互換性の問題やパフォーマンス上の問題については保証できず、責任も負いません。

グローバルファイルキャッシュは、グローバルファイルキャッシュが有効なインスタンス（コアまたはエッジ）に監視ソリューションやアンチウイルスソリューションをインストールしたり、適用したりすることは推奨しません。ソリューションをインストールするか、選択したか、またはポリシーに基づいて、次のベストプラクティスと推奨事項を適用する必要があります。一般的なウィルス対策スイートについては、の付録 A を参照してください link:https://repo.cloudsync.netapp.com/gfc/NetApp%20GFC%20-%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]。



=== ファイアウォールの設定

* Microsoft ファイアウォール：
+
** ファイアウォールの設定をデフォルトのままにします。
** 推奨事項： Microsoft のファイアウォール設定とサービスはデフォルト設定の off のままにしておき、標準のグローバルファイルキャッシュエッジインスタンスでは起動しないようにしてください。
** 推奨事項： Microsoft のファイアウォール設定とサービスはデフォルト設定の on のままにし、ドメインコントローラの役割も実行する Edge インスタンスに対して開始します。


* 企業ファイアウォール：
+
** グローバルファイルキャッシュコアインスタンスは TCP ポート 6618-6630 でリッスンし、グローバルファイルキャッシュエッジインスタンスがこれらの TCP ポートに接続できることを確認します。
** グローバルファイルキャッシュインスタンスは、 TCP ポート 443 （ HTTPS ）上のグローバルファイルキャッシュ管理サーバと通信する必要があります。


* グローバルファイルキャッシュ固有のポートをパススルーするように、ネットワーク最適化ソリューション / デバイスを設定する必要があります。




=== ウィルス対策のベストプラクティス

このセクションでは、グローバルファイルキャッシュを実行している Windows Server インスタンスでアンチウイルスソフトウェアを実行する場合の要件について説明します。Global File Cache は、 Cylance 、 McAfee 、 Symantec 、 Sophos 、 Trend Micro 、 Kaspersky 、 Windows Defender など、一般的に使用されているウイルス対策製品を、 Global File Cache と組み合わせて使用してテストしています。


NOTE: Edge アプライアンスにウィルス対策を追加すると、ユーザのパフォーマンスが 10~20% 低下する可能性があります。

詳細については、を参照してください link:https://repo.cloudsync.netapp.com/gfc/NetApp%20GFC%20-%20User%20Guide.pdf["『 NetApp Global File Cache User Guide 』を参照してください"^]。



==== 除外を設定します

ウイルス対策ソフトウェアまたはその他のサードパーティ製のインデックス付けまたはスキャンユーティリティでは、 Edge インスタンス上のドライブ D ： \ をスキャンしないでください。Edge サーバードライブ D:\ をスキャンすると、キャッシュネームスペース全体に対する多数のファイルオープン要求が発生します。これにより、データセンターで最適化されているすべてのファイルサーバに対して、 WAN 経由でファイルがフェッチされます。WAN 接続フラッディングおよび Edge インスタンス上の不要な負荷が発生すると、パフォーマンスが低下します。

D:\ ドライブに加えて、一般に、次のグローバルファイルキャッシュディレクトリとプロセスをすべてのアンチウイルスアプリケーションから除外する必要があります。

* C ： \Program Files\TalonFAST\`
* C:\Program Files\TalonFAST\Bin\LMClientService.exe`
* C:\Program Files\TalonFAST\Bin\LMServerService.exe`
* C ： \Program Files\TalonFAST\Bin\Optimus.exe
* C ： \Program Files\TalonFAST\Bin\tafsexport.exe
* C:\Program Files\TalonFAST\Bin\tafsutils.exe`
* C ： \Program Files\TalonFAST\Bin\Tapp.exe`
* C ： \Program Files\TalonFAST\Bin\TFS.exe`
* C ： \Program Files\TalonFAST\Bin\TService.exe`
* C ： \Program Files\TalonFAST\Bin\TUM.exe`
* C ： \Program Files\TalonFAST\FastDebugLogs\`
* C:\Windows\System32\drivers\tfast.sys
* 「 \\?\\TafsMtP:\ 」または「 \\?\tafsMtPt*` 」
* \\Device\TalonCacheFS\`
* \\?\GLOBALROOT\Device\TalonCacheFS\`
* \\?\GLOBALROOT\Device\TalonCacheFS\*`




== ネットアップサポートポリシー

グローバルファイルキャッシュインスタンスは、 Windows Server 2016 および 2019 プラットフォームで実行されるプライマリアプリケーションとして、グローバルファイルキャッシュ専用に設計されています。グローバルファイルキャッシュには、ディスク、メモリ、ネットワークインターフェイスなどのプラットフォームリソースへの優先的なアクセスが必要であり、これらのリソースに高い負荷を与えることができます。仮想環境では、メモリ / CPU の予約とハイパフォーマンスディスクが必要です。

* グローバルファイルキャッシュを展開するブランチオフィスの場合、グローバルファイルキャッシュを実行するサーバ上でサポートされるサービスとアプリケーションは次のように制限されます。
+
** DNS/DHCP
** Active Directory ドメインコントローラ （グローバルファイルキャッシュは別のボリュームに配置する必要があります）
** プリントサービス
** Microsoft System Center Configuration Manager （ SCCM ）
** Global File Cache が承認したクライアント側システムエージェントとウィルス対策アプリケーション


* ネットアップのサポートとメンテナンスはグローバルファイルキャッシュにのみ適用されます。
* データベースサーバやメールサーバなど、リソースを大量に消費する基幹業務生産性ソフトウェアはサポートされていません。
* グローバルファイルキャッシュを実行しているサーバーにインストールされているグローバルファイルキャッシュ以外のソフトウェアについては、お客様の責任となります。
+
** サードパーティ製のソフトウェアパッケージが原因で、ソフトウェアやリソースがグローバルファイルキャッシュと競合したり、パフォーマンスが低下したりする場合は、グローバルファイルキャッシュのサポート組織が、グローバルファイルキャッシュを実行しているサーバでソフトウェアを無効にしたり、削除したりするようにお客様に要求することがあります。
** Global File Cache アプリケーションを実行しているサーバに追加されたすべてのソフトウェアのインストール、統合、サポート、アップグレードは、お客様の責任で行ってください。


* ウイルス対策ツールやライセンスエージェントなどのシステム管理ユーティリティ / エージェントは、共存できます。ただし、前述のサポートされているサービスとアプリケーションを除き、これらのアプリケーションはグローバルファイルキャッシュでサポートされていません。また、上記と同じガイドラインに従う必要があります。
+
** 追加したソフトウェアのインストール、統合、サポート、アップグレードは、お客様の責任で行ってください。
** お客様が、ソフトウェアまたはリソースがグローバルファイルキャッシュと競合したり、パフォーマンスが低下したりする原因と思われるサードパーティ製ソフトウェアパッケージをインストールした場合、グローバルファイルキャッシュのサポート組織がソフトウェアを無効化または削除する必要がある場合があります。



