---
sidebar: sidebar 
permalink: faq_saas.html 
keywords: faq, frequently asked questions, questions 
summary: この FAQ では、新しい Cloud Manager SaaS リリースに関連する主な質問とその回答を記載しています。 
---
= Cloud Manager SaaS に関する FAQ です
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この FAQ では、新しい Cloud Manager SaaS リリースに関連する主な質問とその回答を記載しています。



== 2020 年 8 月 3 日に Cloud Manager SaaS リリースに導入された機能はどれですか？

* * 統一された API と UI *
+
NetApp ONTAP ベースのすべてのストレージソリューションを対象とした一元化された統合型の API コントロールプレーンで、お客様は次の項目を管理、制御できます。

+
** Azure NetApp Files の特長
** Cloud Volumes Service for AWS
** Cloud Volumes Service for Google Cloud
** Cloud Volumes ONTAP


* * ネットアップのデータサービスとのシームレスな統合 *
+
スムーズな統合を実現するため、ストレージソリューションには統合が容易なデータサービスが組み込まれています。

* * 複数の環境の一元管理 *
+
複数の環境の導入と管理が簡易化されました。以前のリリースでは、 Cloud Manager インスタンスを必要なすべての場所に導入する必要がありました。新しいリリースでは、 Cloud Manager エージェントの名前が _Connector_connector_ に変更されました。

+
複数の NetApp Cloud Central アカウントまたはコネクタを持つユーザは、異なるアカウント間や異なる環境間で簡単に切り替えることができます。

* * API および UI のパブリックエンドポイント *
+
新しいリリースでは、 API とにアクセスできます を使用して、 Cloud Manager 用の GUI をセキュアに設定できます  https://cloudmanager.netapp.com[]。





== VPC / VNet に導入された Cloud Manager インスタンスはどうなりますか。

前述のように、お客様のネットワークに導入された Cloud Manager インスタンスは、 _ コネクタ _ と呼ばれるようになりました。

コネクタの役割は変更されていません。お客様のパブリッククラウドネットワーク内のリソースとプロセスを管理する目的は、従来と同じです。



== SaaS プラットフォームを使用しているのでコネクタを取り外してもよろしいですか？

いいえ、できません。Connector は、 Cloud Volumes ONTAP の導入と管理、 Cloud Backup Service の有効化、クラウドコンプライアンスの導入など、パブリッククラウド環境内でリソースとプロセスを管理するために使用されたソフトウェアと同じです。



== 以前と同じ方法で Cloud Manager を使用できますか（ VPC に導入されたインスタンスを使用してローカルで実行）？

はい。 * コネクター * メニューをクリックし、 * ローカル UI へ移動 * をクリックするか、コネクターの IP アドレスを Web ブラウザーに直接入力することで、この操作を行うことができます。



== 移行や、 Cloud Manager SaaS への移行に必要な具体的な対応はありますか。

必要はありません。参照してください https://cloudmanager.netapp.com[] 作業を開始します。Cloud Manager へのアクセスは、許可されたユーザにのみ許可されます。



== Cloud Volumes ONTAP または保存されているデータは変化しましたか？それともどこにでも移動しましたか？

いいえVPC または VNet 内で管理下に常に存在しています。



== Cloud Manager SaaS プラットフォームのエンドポイントはどこにありますか。

ネットアップがパブリッククラウドでセキュアに運用しています。



== Cloud Manager SaaS サービスレイヤにはどのような種類のデータやメタデータが格納されていますか？

Cloud Manager SaaS サービスレイヤにデータが格納されることはありません。

SaaS プラットフォームは、ユーザの Web ブラウザとローカルコネクタ間、または Cloud Manager に統合された各種ネットアップサービス間の API コール（ネットアップ署名証明書付き HTTPS ）の安全なパイプラインとして使用されます。



== VPC / VNet に導入されたコネクタによって格納されるデータやメタデータは何ですか。

コネクタ / Cloud Manager は変更されていません。以前のリリースと同じデータが保存されています。Cloud Volumes ONTAP の導入と管理、 Cloud Backup Service の有効化、 Cloud Compliance の導入と使用など、パブリッククラウド環境でリソースとプロセスを管理するために必要なメタデータのみを保持します（を参照） link:concept_connectors.html["コネクタについて説明します"] ページを参照してください）。



== データパスとメタデータパスについて教えてください。

コネクタからお客様へのデータは HTTPS 経由で転送され、ネットアップの証明書で暗号化されて署名されます。SaaS ベースの UI は、クライアントの Web ブラウザとコネクタの間のセキュアなパイプラインとして機能します。これは、許可されたユーザーのみがコネクタからのデータにアクセスできることを意味します。

Cloud Compliance サービスを利用するお客様は、エンドツーエンドで暗号化されるようになりましたWeb ブラウザとコネクタの間で鍵の交換が行われるため、ネットアップはデータを読み取ることができません。 https://cloud.netapp.com/cloud-compliance["Cloud Compliance の詳細はこちらをご覧ください"^]。



== SaaS エンドポイント経由で Cloud Compliance サービスを使用すると、 GDPR の影響はありますか。

データはエンドツーエンドで暗号化されますWeb ブラウザとコネクタの間で鍵の交換が行われるため、ネットアップはデータを読み取ることができません。



== SaaS ベースの UI および API からコネクタへのアクセスに使用されるネットワーク方向アクセスの種類を教えてください。

* お客様の VPC / VNet から SaaS ベースの UI への通信は _OUTBOUND _ のみであるため、コネクタによってのみ開始されます。
* コネクタは、セキュアなチャネル上で SaaS ベースのサービス層からアップデートをポーリングします。
* すべての API 呼び出しで、認証と許可を使用してアクセスが保護されていることを確認します。
+
つまり、ネットワーク内のポートやエンドポイントを開く必要がなくなります。

* ユーザのブラウザクライアントと SaaS ベースの UI 間の通信には、ネットアップ署名証明書を使用した HTTPS が使用されます。




== ログインフローは変化しましたか。

いいえ。ログインフローは以前のリリースと同じです。ユーザがログインすると（ SSO またはクレデンシャル）、認証は以前と同様に Auth0 に対して行われます。

次の点に注意してください。

* SSO またはフェデレーションが設定されている場合は、使用されていたのと同じセキュリティ手順がまだ実行されています。会社の施設では、アクセスが連携しています。連携アクセスを利用する場合は、（会社の裁量で） MFA を追加してセキュリティを強化できます。
* ロールまたは権限に変更はありません。SaaS ベースのエンドポイントにアクセスできるのは、 Cloud Central アカウントに登録されているユーザのみです。
* incognito モードの使用、またはクライアントブラウザでサードパーティのクッキーが許可されていない設定は現在サポートされていません。




== SaaS ベースの Cloud Manager （ SOC2 、 FedRAMP など）は準拠していますか？

Cloud Manager は SOC2 認定を取得中です。

FedRAMP 認定に従い、 FedRAMP を必要とするお客様に対しては SaaS ベースの UI が有効になりません。
