---
sidebar: sidebar 
permalink: faq_sync.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support 
summary: Cloud Sync のヘルプを表示したり、フォーラム、チャットサービス、ビデオなどのさまざまなリソースを使用して詳細情報を確認したりできます。 
---
= Cloud Sync テクニカル FAQ
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== はじめに

次の質問は、クラウド同期の導入に関連しています。



=== クラウド同期の仕組み

Cloud Sync では、ネットアップデータブローカーソフトウェアを使用して、ソースからターゲット（「 a_sync relationship_ 」）にデータを同期します。

データブローカーは、ソースとターゲット間の同期関係を制御します。同期関係を設定すると、 Cloud Sync はソースシステムを分析し、選択したターゲットデータにプッシュするために複数のレプリケーションストリームに分割します。

最初のコピーの後、設定したスケジュールに基づいて変更されたデータが同期されます。



=== 14 日間の無料トライアルはどのように機能しますか？

14 日間の無料トライアルは、 Cloud Sync サービスにサインアップすると開始されます。14 日間にわたって作成した Cloud Sync 関係については、ネットアップが料金を支払う必要はありません。ただし、展開するデータブローカーのすべてのリソース料金は引き続き適用されます。



=== クラウド同期のコストはいくらですか。

Cloud Sync の使用に関連するコストには、サービス料金とリソース料金の 2 種類があります。

* サービス料金 *

従量課金制の場合、 Cloud Sync サービス料金は、作成する同期関係の数に基づいて 1 時間ごとに課金されます。

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["AWS で従量課金制の価格を確認できます"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWS の年間価格を確認します"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Azure で価格を表示します"^]


Cloud Sync ライセンスは、ネットアップの担当者からも入手できます。各ライセンスでは、 12 カ月間で 20 の同期関係が有効になります。

link:concept_cloud_sync.html["ライセンスの詳細については、こちらをご覧ください。"]。

* リソース料金 *

リソース料金は、クラウドでデータブローカーを実行するためのコンピューティングコストとストレージコストに関連しています。



=== Cloud Sync の料金はどのように設定されますか

14 日間の無料トライアル終了後に、同期関係の料金を支払う方法は 2 通りあります。最初のオプションは、 AWS または Azure から購読することです。 AWS または Azure を使用すると、従量課金制または年払いが可能になります。2 つ目の選択肢は、ネットアップから直接ライセンスを購入することです。



=== クラウドの外部でクラウド同期を使用できますか。

はい。クラウド同期は非クラウドアーキテクチャで使用できます。ソースとターゲットはオンプレミスに配置できるため、データブローカーも配置できます。

Cloud Sync をクラウドの外部で使用する場合、次の点に注意してください。

* オンプレミス同期の場合、プライベート Amazon S3 バケットを NetApp StorageGRID で利用できます。
* データブローカーは、 Cloud Sync サービスと通信するためにインターネット接続が必要です。
* ネットアップからライセンスを直接購入しない場合は、従量課金制の Cloud Sync サービスを利用する AWS または Azure のアカウントが必要です。




=== Cloud Sync へのアクセス方法を教えてください。

Cloud Sync は、 Cloud Manager の * Sync * タブで使用できます。



== サポートされているソースとターゲット

同期関係でサポートされているソースとターゲットに関連する次の質問。



=== Cloud Sync がサポートするソースとターゲットはどれですか。

クラウド同期では、さまざまな種類の同期関係がサポートされています。 link:reference_sync_requirements.html["リスト全体を表示します。"]。



=== クラウド同期でサポートされる NFS と SMB のバージョンを教えてください。

クラウド同期では、 NFS バージョン 3 以降、 SMB バージョン 1 以降がサポートされます。

link:reference_sync_requirements.html["同期の要件の詳細については、こちらをご覧ください。"]。



=== Amazon S3 がターゲットである場合、特定の S3 ストレージクラスにデータを階層化できますか。

はい。 AWS S3 がターゲットである場合は、特定の S3 ストレージクラスを選択できます。

* 標準（これがデフォルトクラス）
* インテリジェント階層化
* 標準的なアクセス頻度は低い
* 1 回のアクセスではほとんど発生しません
* 氷河
* Glacier Deep Archive




=== Azure BLOB ストレージのストレージ階層について教えてください。

BLOB コンテナがターゲットの場合は、特定の Azure BLOB ストレージ階層を選択できます。

* ホットストレージ
* 優れたストレージ




== ネットワーキング

次の質問は、クラウド同期のネットワーク要件に関連しています。



=== クラウドの同期に必要なネットワーク要件は何ですか？

クラウド同期環境では、データブローカーが、選択したプロトコル（ NFS 、 SMB 、 EFS ）またはオブジェクトストレージ API （ Amazon S3 、 Azure BLOB 、 IBM Cloud Object Storage ）を介してソースとターゲットに接続されている必要があります。

さらに、データブローカーは、ポート 443 を介したアウトバウンドインターネット接続を必要とします。これにより、データブローカーは Cloud Sync サービスと通信し、他のいくつかのサービスやリポジトリに接続できます。

詳細： link:reference_sync_networking.html["ネットワーク要件を確認します。"]。



=== データブローカーの接続に関連するネットワークの制限はありますか？

データブローカーにはインターネットアクセスが必要です。Azure または Google Cloud Platform にデータブローカーを導入する場合、プロキシサーバはサポートされません。



== データの同期

次の質問は、データ同期の仕組みに関連しています。



=== 同期はどのくらいの頻度で行われますか。

デフォルトのスケジュールは、毎日の同期に設定されています。初期同期化の後、次の操作を実行できます。

* 同期スケジュールを、希望する日数、時間数、分数に変更します
* 同期スケジュールを無効にします
* 同期スケジュールを削除します（データは失われません。同期関係のみが削除されます）。




=== 最小同期スケジュールは何ですか？

データを 1 分ごとに同期するように関係をスケジュールできます。



=== ファイルの同期に失敗した場合、データブローカーは再試行しますか？またはタイムアウトしますか？

1 つのファイルの転送が失敗しても、データブローカーはタイムアウトしません。代わりに、データブローカーはファイルをスキップする前に 3 回再試行します。再試行値は、同期関係の設定で設定できます。

link:task_sync_managing_relationships.html#changing-the-settings-for-a-sync-relationship["同期関係の設定を変更する方法について説明します。"]。



=== 非常に大規模なデータセットがある場合はどうすればよいですか。

1 つのディレクトリに 60 万以上のファイルが含まれている場合は、 mailto ： ng-cloudsync-support@netapp.com [ お問い合わせ ] をご利用ください。このため、データブローカーでペイロードを処理するように設定できます。データブローカーマシンにメモリを追加する必要がある場合があります。



== セキュリティ

セキュリティに関する次の質問



=== クラウドの同期は安全ですか？

はい。すべての Cloud Sync サービスのネットワーク接続には、を使用します https://aws.amazon.com/sqs/["Amazon Simple Queue Service （ SQS ）"^]。

データブローカーと Amazon S3 、 Azure Blob 、 Google Cloud Storage 、 IBM Cloud Object Storage 間の通信はすべて、 HTTPS プロトコルを使用して行われます。

オンプレミス（ソースまたはデスティネーション）システムで Cloud Sync を使用している場合、推奨される接続オプションは次のとおりです。

* AWS Direct Connect 、 Azure ExpressRoute 、または Google Cloud Interconnect 接続。インターネット経由ではない（指定したクラウドネットワークとのみ通信可能）
* オンプレミスゲートウェイデバイスとクラウドネットワーク間の VPN 接続
* S3 バケット、 Azure BLOB ストレージ、または Google クラウドストレージを使用した安全なデータ転送のために、 Amazon Private S3 エンドポイント、 Azure Virtual Network サービスエンドポイント、またはプライベート Google アクセスを確立できます。


これらのいずれかの方法で、オンプレミス NAS サーバーとクラウド同期データブローカー間の安全な接続が確立されます。



=== データはクラウド同期で暗号化されていますか？

* クラウド同期では、ソースとターゲットの NFS サーバ間のデータインフライト暗号化がサポートされます。 link:task_sync_nfs_encryption.html["詳細はこちら。"]。
* SMB では暗号化はサポートされていません。
* Amazon S3 バケットが同期関係のターゲットである場合は、 AWS KMS の暗号化と AES-256 暗号化を使用してデータ暗号化を有効にするかどうかを選択できます。




== 権限

次の質問は、データ権限に関連しています。



=== SMB データの権限はターゲットの場所に同期されていますか？

クラウド同期を設定して、ソース SMB 共有とターゲット SMB 共有間のアクセスコントロールリスト（ ACL ）を保持できます。または、 ACL を手動でコピーすることもできます。 link:task_sync_copying_acls.html["SMB 共有間で ACL をコピーする方法について説明します。"]。



=== NFS データの権限はターゲットの場所に同期されていますか。

クラウド同期では、 NFS サーバ間で次のように NFS 権限が自動的にコピーされます。

* NFS バージョン 3 ： Cloud Sync は権限とユーザグループ所有者をコピーします。
* NFS バージョン 4 ： Cloud Sync は ACL をコピーします。




== パフォーマンス

クラウド同期のパフォーマンスに関する質問は次のとおりです。



=== 同期関係の進行状況インジケータは何を表していますか。

同期関係は、データブローカーのネットワークアダプタのスループットを示しています。複数のデータブローカーを使用して同期パフォーマンスを高速化した場合、スループットはすべてのトラフィックの合計になります。このスループットは 20 秒ごとに更新されます。



=== パフォーマンスの問題が発生しています。同時転送の数を制限できますか。

データブローカーは、一度に 4 つのファイルを同期できます。非常に大きなファイルがある場合（それぞれ数 TB ）、転送プロセスが完了するまでに時間がかかることがあり、パフォーマンスが低下する可能性があります。

同時転送の数を制限すると効果的です。mailto ： ng-cloudsync-support@netapp.com [ お問い合わせ ]



=== Azure NetApp Files でパフォーマンスが低いのはなぜですか？

Azure NetApp Files との間でデータを同期する際、ディスクのサービスレベルが Standard の場合は障害やパフォーマンスの問題が発生することがあります。

同期パフォーマンスを向上させるには、サービスレベルを Premium または Ultra に変更します。

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["Azure NetApp Files のサービスレベルとスループットの詳細については、こちらをご覧ください"^]。



=== Cloud Volumes Service for AWS でパフォーマンスが低下するのはなぜですか。

クラウドボリュームとの間でデータを同期する場合、クラウドボリュームのパフォーマンスレベルが標準の場合は、障害やパフォーマンスの問題が発生することがあります。

サービスレベルを Premium または Extreme に変更して、同期のパフォーマンスを向上させます。



=== 必要なデータブローカーの数はいくつですか？

新しい関係を作成する場合は、 1 つのデータブローカーから始めます（高速同期関係に属する既存のデータブローカーを選択した場合を除く）。多くの場合、 1 つのデータブローカーで同期関係のパフォーマンス要件を満たすことができます。同期されていない場合は、データブローカーを追加することで、同期パフォーマンスを高速化できます。ただし、まず、同期のパフォーマンスに影響を与える可能性のある他の要因を確認する必要があります。

データ転送のパフォーマンスには、複数の要因が影響します。全体的な同期パフォーマンスは、ネットワーク帯域幅、レイテンシ、ネットワークトポロジ、データブローカー VM の仕様、ストレージシステムのパフォーマンスによって影響を受ける可能性があります。たとえば、同期関係にある単一のデータブローカーは 100 MB/ 秒に到達できますが、ターゲットのディスクスループットは 64 MB/ 秒にしか対応できない場合があります。その結果、データブローカーはデータのコピーを試み続けていますが、ターゲットではデータブローカーのパフォーマンスを満たせません。

そのため、ネットワークのパフォーマンスとターゲットのディスクスループットを確認してください。

その後、データブローカーを追加して、その関係の負荷を共有することで、同期のパフォーマンスを向上させることを検討できます。 link:task_sync_managing_relationships.html#accelerating-sync-performance["同期のパフォーマンスを高速化する方法について説明します。"]。



== 項目を削除する

次の質問は、ソースとターゲットから同期関係とデータを削除することに関連しています。



=== クラウドの同期関係を削除するとどうなりますか。

関係を削除すると、以降のすべてのデータの同期が停止し、支払いが終了します。ターゲットに同期されたデータはそのまま残ります。



=== ソースサーバから何かを削除するとどうなりますか。ターゲットからも削除されていますか？

デフォルトでは、 Active Sync 関係がある場合、ソースサーバ上で削除されたアイテムは、次回の同期時にターゲットから削除されません。ただし、各関係の同期設定にはオプションがあり、ソースから削除されたファイルは Cloud Sync によってターゲットロケーションから削除されるように定義できます。

link:task_sync_managing_relationships.html#changing-the-settings-for-a-sync-relationship["同期関係の設定を変更する方法について説明します。"]。



=== ターゲットから何かを削除するとどうなりますか？ソースからも削除されていますか？

ターゲットから削除されたアイテムは、ソースから削除されません。ソースからターゲットへの関係は一方向です。次の同期サイクルでは、クラウド同期によってソースとターゲットが比較され、アイテムが見つからないことが特定され、クラウド同期によってソースからターゲットに再度コピーされます。



== トラブルシューティング

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["ネットアップナレッジベース： Cloud Sync FAQ ： Support and Troubleshooting"^]



== データブローカーのディープダイブ

次の質問は、データブローカーに関連しています。



=== データブローカーのアーキテクチャについて説明できますか？

確かに。最も重要なポイントは次のとおりです。

* データブローカーは、 Linux ホスト上で実行されている Node.js アプリケーションです。
* Cloud Sync は、次のようにデータブローカーを導入します。
+
** AWS ： AWS Cloudformation テンプレートから
** Azure ： Azure Resource Manager から
** Google ： Google Cloud Deployment Manager から
** 独自の Linux ホストを使用する場合は、ソフトウェアを手動でインストールする必要があります


* データブローカーソフトウェアは、自動的に最新バージョンにアップグレードします。
* データブローカーは、 AWS SQS を信頼性の高い安全な通信チャネルとして使用し、制御と監視を行います。SQS は永続性レイヤも提供します。
* データブローカーをリレーションシップに追加して、転送速度を向上させ、高可用性を高めることができます。1 つのデータブローカーに障害が発生した場合、サービスの耐障害性があります

