---
settings:
  name: Cloud Manager 3.8
  nss_product: OnCommand Cloud Manager
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,zh-cn,zh-tw,ko-kr,fr-fr,de-de
sidebar:
  entries:
  - title: Cloud Manager のドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: クラウドマネージャ
      entries:
      - title: 新機能
        url: "/reference_new_occm.html"
      - title: SaaS への移行
        url: "/concept_saas.html"
      - title: 既知の問題
        url: "/reference_issues.html"
      - title: 既知の制限
        url: "/reference_limitations.html"
    - title: Cloud Volumes ONTAP
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap/
  - title: 重要な変更
    url: "/reference_key_changes.html"
  - title: Cloud Manager の使用を開始
    entries:
    - title: Cloud Manager の詳細をご確認ください
      url: "/concept_overview.html"
    - title: ネットワークの概要
      url: "/reference_networking.html"
    - title: Cloud Central に登録します
      url: "/task_signing_up.html"
    - title: Cloud Manager にログインします
      url: "/task_logging_in.html"
    - title: Cloud Central アカウントをセットアップします
      entries:
      - title: Cloud Central アカウントについて詳しくは、こちらをご覧ください
        url: "/concept_cloud_central_accounts.html"
      - title: アカウントを設定します
        url: "/task_setting_up_cloud_central_accounts.html"
    - title: コネクタをセットアップします
      entries:
      - title: コネクタについて説明します
        url: "/concept_connectors.html"
      - title: ネットワーク要件
        url: "/reference_networking_cloud_manager.html"
      - title: AWS でコネクタを作成します
        url: "/task_creating_connectors_aws.html"
      - title: Azure でコネクタを作成します
        url: "/task_creating_connectors_azure.html"
      - title: GCP でコネクターを作成します
        url: "/task_creating_connectors_gcp.html"
    - title: 次の手順
      url: "/reference_whats_next.html"
  - title: Cloud Volumes ONTAP を管理します
    entries:
    - title: 詳細はこちら
      entries:
      - title: 概要
        url: "/concept_overview_cvo.html"
      - title: ストレージ
        entries:
        - title: ディスクとアグリゲート
          url: "/concept_storage.html"
        - title: データの階層化
          url: "/concept_data_tiering.html"
        - title: ストレージ管理
          url: "/concept_storage_management.html"
        - title: Flash Cache
          url: "/concept_flash_cache.html"
        - title: WORM ストレージ
          url: "/concept_worm.html"
      - title: ハイアベイラビリティペア
        entries:
        - title: AWS の HA ペア
          url: "/concept_ha.html"
        - title: Azure の HA ペア
          url: "/concept_ha_azure.html"
      - title: 評価中
        url: "/concept_evaluating.html"
      - title: ライセンス
        url: "/concept_licensing.html"
      - title: セキュリティ
        url: "/concept_security.html"
      - title: パフォーマンス
        url: "/concept_performance.html"
      - title: サポートされている構成
        url: https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html
      - title: サポートされている地域
        url: https://cloud.netapp.com/cloud-volumes-global-regions
      - title: デフォルト設定
        url: "/reference_default_configs.html"
    - title: AWS を始めましょう
      entries:
      - title: クイックスタート
        url: "/task_getting_started_aws.html"
      - title: 構成を計画
        url: "/task_planning_your_config.html"
      - title: ネットワークをセットアップします
        entries:
        - title: ネットワーク要件
          url: "/reference_networking_aws.html"
        - title: AWS 転送ゲートウェイを設定します
          url: "/task_setting_up_transit_gateway.html"
        - title: AWS のセキュリティグループルール
          url: "/reference_security_groups.html"
      - title: AWS KMS を設定します
        url: "/task_setting_up_kms.html"
      - title: AWS でシステムを起動します
        url: "/task_deploying_otc_aws.html"
      - title: AWS C2S で作業を開始する
        url: https://docs.netapp.com/us-en/occm/media/c2s.pdf
    - title: Azure で始めましょう
      entries:
      - title: クイックスタート
        url: "/task_getting_started_azure.html"
      - title: 構成を計画
        url: "/task_planning_your_config_azure.html"
      - title: ネットワークをセットアップします
        url: "/reference_networking_azure.html"
      - title: Azure でシステムを起動します
        url: "/task_deploying_otc_azure.html"
    - title: GCP を始めましょう
      entries:
      - title: クイックスタート
        url: "/task_getting_started_gcp.html"
      - title: 構成を計画
        url: "/task_planning_your_config_gcp.html"
      - title: ネットワークをセットアップします
        url: "/reference_networking_gcp.html"
      - title: お客様が管理する暗号化キーを使用します
        url: "/task_setting_up_gcp_encryption.html"
      - title: GCP でシステムを起動します
        url: "/task_deploying_gcp.html"
    - title: ストレージをプロビジョニングおよび管理する
      entries:
      - title: ボリューム、アグリゲート、および LUN を作成する
        url: "/task_provisioning_storage.html"
      - title: ボリュームおよびアグリゲートを管理する
        url: "/task_managing_storage.html"
      - title: アクセス頻度の低いデータをオブジェクトストレージに階層化します
        url: "/task_tiering.html"
      - title: Storage VM を管理します
        url: "/task_managing_svms.html"
      - title: ONTAP を永続的ストレージとして使用する
        url: "/task_connecting_kubernetes.html"
      - title: ネットアップの暗号化機能でボリュームを暗号化
        url: "/task_encrypting_volumes.html"
    - title: データのレプリケート
      url: "/task_replicating_data.html"
    - title: パフォーマンスを監視
      entries:
      - title: モニタリングについて説明します
        url: "/concept_monitoring.html"
      - title: はじめに
        url: "/task_getting_started_monitoring.html"
    - title: ランサムウェアからの保護を強化
      url: "/task_protecting_ransomware.html"
    - title: 管理
      entries:
      - title: 従量課金制システムを登録
        url: "/task_registering.html"
      - title: Cloud Volumes ONTAP をセットアップする
        url: "/task_setting_up_ontap_cloud.html"
      - title: BYOL ライセンスを管理します
        url: "/task_managing_licenses.html"
      - title: ソフトウェアを更新します
        url: "/task_updating_ontap_cloud.html"
      - title: システム設定を変更する
        url: "/task_modifying_ontap_cloud.html"
      - title: システムを停止して起動します
        url: "/task_managing_state.html"
      - title: AWS のコストを監視
        url: "/task_monitoring_costs.html"
      - title: Cloud Volumes ONTAP に接続します
        url: "/task_connecting_to_otc.html"
      - title: 既存のシステムを追加
        url: "/task_adding_ontap_cloud.html"
      - title: システムを削除します
        url: "/task_deleting_working_env.html"
  - title: ファイルサービスを使用してボリュームをプロビジョニング
    entries:
    - title: Azure NetApp Files の特長
      entries:
      - title: Azure NetApp Files の詳細をご覧ください
        url: "/concept_azure_netapp_files.html"
      - title: Azure NetApp Files をセットアップする
        url: "/task_manage_anf.html"
      - title: ボリュームを作成および管理する
        url: "/task_manage_anf_volumes.html"
    - title: Cloud Volumes Service for AWS
      entries:
      - title: Cloud Volumes Service for AWS の詳細については、こちらをご覧ください
        url: "/concept_cvs_aws.html"
      - title: クラウドボリュームを導入して管理
        url: "/task_manage_cvs_aws.html"
      - title: クラウドボリュームの Snapshot を管理します
        url: "/task_manage_cloud_volumes_snapshots.html"
      - title: 参照
        entries:
        - title: サービスレベルと割り当て容量
          url: "/reference_cvs_service_levels_and_quotas.html"
        - title: Windows AD サーバ用の AWS セキュリティグループの設定
          url: "/reference_security_groups_windows_ad_servers.html"
    - title: Cloud Volumes Service for GCP
      entries:
      - title: Cloud Volumes Service for GCP について説明します
        url: "/concept_cvs_gcp.html"
      - title: Cloud Volumes Service for GCP をセットアップします
        url: "/task_setup_cvs_gcp.html"
      - title: クラウドボリュームを作成および管理します
        url: "/task_manage_cvs_gcp.html"
      - title: クラウドボリュームの Snapshot を管理します
        url: "/task_manage_cloud_volumes_gcp_snapshots.html"
  - title: ONTAP クラスタを管理します
    entries:
    - title: ONTAP クラスタを検出
      url: "/task_discovering_ontap.html"
    - title: ONTAP ボリュームを管理します
      url: "/task_provisioning_ontap.html"
  - title: クラウドへのバックアップ
    entries:
    - title: クラウドへのバックアップの詳細をご確認ください
      url: "/concept_backup_to_cloud.html"
    - title: はじめに
      entries:
      - title: Amazon S3 にバックアップします
        url: "/task_backup_to_s3.html"
      - title: Azure BLOB ストレージにバックアップします
        url: "/task_backup_to_azure.html"
      - title: オンプレミスの ONTAP システムからバックアップ
        url: "/task_backup_from_onprem.html"
    - title: バックアップの管理とデータのリストア
      url: "/task_managing_backups.html"
  - title: データをコピーして同期
    entries:
    - title: クラウドの同期についてご確認ください
      url: "/concept_cloud_sync.html"
    - title: はじめに
      entries:
      - title: クイックスタート
        url: "/task_sync_quick_start.html"
      - title: ソースとターゲットを準備します
        url: "/reference_sync_requirements.html"
      - title: ネットワークを準備
        url: "/reference_sync_networking.html"
      - title: データブローカーのインストール方法
        entries:
        - title: AWS にインストールします
          url: "/task_sync_installing_aws.html"
        - title: Azure にインストール
          url: "/task_sync_installing_azure.html"
        - title: GCP にインストールします
          url: "/task_sync_installing_gcp.html"
        - title: Linux ホストにをインストールします
          url: "/task_sync_installing_linux.html"
      - title: 同期関係を作成します
        url: "/task_sync_creating_relationships.html"
      - title: 同期関係の料金を支払う
        url: "/task_sync_licensing.html"
    - title: チュートリアル
      entries:
      - title: 共有間で ACL をコピーする
        url: "/task_sync_copying_acls.html"
      - title: 転送中の NFS データを暗号化
        url: "/task_sync_nfs_encryption.html"
    - title: 同期関係を管理します
      url: "/task_sync_managing_relationships.html"
    - title: API
      url: "/api_sync.html"
    - title: よく寄せられる質問
      url: "/faq_sync.html"
  - title: データプライバシーに関する分析情報を入手できます
    entries:
    - title: Cloud Compliance の詳細をご確認ください
      url: "/concept_cloud_compliance.html"
    - title: はじめに
      entries:
      - title: Cloud Compliance の導入
        url: "/task_deploy_cloud_compliance.html"
      - title: データソースでスキャンをアクティブ化します
        entries:
        - title: Cloud Volumes ONTAP および Azure NetApp Files
          url: "/task_getting_started_compliance.html"
        - title: Amazon S3 バケット
          url: "/task_scanning_s3.html"
        - title: データベーススキーマ
          url: "/task_scanning_databases.html"
        - title: オンプレミスの ONTAP データ
          url: "/task_scanning_onprem.html"
    - title: データの可視化と管理を実現
      url: "/task_controlling_private_data.html"
    - title: レポートを生成します
      url: "/task_generating_compliance_reports.html"
    - title: dsar に応答します
      url: "/task_responding_to_dsar.html"
    - title: クラウドコンプライアンスを無効化
      url: "/task_managing_compliance.html"
    - title: よく寄せられる質問
      url: "/faq_cloud_compliance.html"
  - title: リアルタイムのグローバルファイル共有を有効にします
    entries:
    - title: グローバルファイルキャッシュについて説明します
      url: "/concept_gfc.html"
    - title: グローバルファイルキャッシュの導入を開始する前に
      url: "/concept_before_you_begin_to_deploy_gfc.html"
    - title: はじめに
      url: "/task_gfc_getting_started.html"
    - title: グローバルファイルキャッシュエッジの導入を開始する前に
      url: "/download_gfc_resources.html"
    - title: グローバルファイルキャッシュエッジを導入します
      url: "/task_deploy_gfc_edge_instances.html"
    - title: エンドユーザトレーニング
      url: "/concept_gfc_enduser_training.html"
    - title: 追加情報
      url: "/reference_gfc_additional_information.html"
  - title: クラウドコンピューティングのコストを最適化
    entries:
    - title: コンピューティングサービスの詳細については、こちらをご覧ください
      url: "/concept_compute.html"
    - title: はじめに
      url: "/task_getting_started_compute.html"
  - title: データをクラウドに階層化
    entries:
    - title: Cloud Tiering の詳細をご確認ください
      url: "/concept_cloud_tiering.html"
    - title: はじめに
      entries:
      - title: データを Amazon S3 に階層化する
        url: "/task_tiering_onprem_aws.html"
      - title: データを Azure BLOB ストレージに階層化する
        url: "/task_tiering_onprem_azure.html"
      - title: データを Google Cloud Storage に階層化します
        url: "/task_tiering_onprem_gcp.html"
      - title: データを StorageGRID に階層化します
        url: "/task_tiering_onprem_storagegrid.html"
    - title: ライセンスをセットアップする
      url: "/task_licensing_cloud_tiering.html"
    - title: データの階層化を管理します
      url: "/task_managing_tiering.html"
    - title: よく寄せられる質問
      url: "/faq_cloud_tiering.html"
    - title: 参照
      entries:
      - title: サポートされている Amazon S3 ストレージのクラスとリージョン
        url: "/reference_aws_support.html"
      - title: サポートされている Azure アクセス階層とリージョン
        url: "/reference_azure_support.html"
      - title: サポートされている Google Cloud ストレージクラスとリージョン
        url: "/reference_google_support.html"
  - title: Amazon S3 バケットを表示します
    url: "/task_viewing_amazon_s3.html"
  - title: Cloud Manager の管理
    entries:
    - title: システム ID を確認します
      url: "/task_finding_system_id.html"
    - title: コネクタを管理します
      entries:
      - title: 既存のコネクタを管理します
        url: "/task_managing_connectors.html"
      - title: コネクタを作成するさまざまな方法
        entries:
        - title: Connector ホストの要件
          url: "/reference_cloud_mgr_reqs.html"
        - title: AWS Marketplace から作成します
          url: "/task_launching_aws_mktp.html"
        - title: Azure Marketplace から作成
          url: "/task_launching_azure_mktp.html"
        - title: ソフトウェアを手動でインストールします
          url: "/task_installing_linux.html"
      - title: デフォルト設定
        url: "/reference_connector_default_config.html"
    - title: クレデンシャルを管理する
      entries:
      - title: AWS
        entries:
        - title: AWS クレデンシャルの詳細を確認します
          url: "/concept_accounts_aws.html"
        - title: AWS クレデンシャルを管理する
          url: "/task_adding_aws_accounts.html"
      - title: Azure
        entries:
        - title: Azure のクレデンシャルについて説明します
          url: "/concept_accounts_azure.html"
        - title: Azure クレデンシャルを管理します
          url: "/task_adding_azure_accounts.html"
      - title: GCP
        entries:
        - title: GCP クレデンシャルについて説明します
          url: "/concept_accounts_gcp.html"
        - title: GCP クレデンシャルを管理する
          url: "/task_adding_gcp_accounts.html"
      - title: ネットアップサポートサイトのクレデンシャル
        url: "/task_adding_nss_accounts.html"
    - title: アカウントを管理します
      url: "/task_managing_cloud_central_accounts.html"
    - title: HTTPS 証明書をインストールします
      url: "/task_installing_https_cert.html"
    - title: 作業環境を削除します
      url: "/task_removing.html"
    - title: プロキシを設定します
      url: "/task_configuring_proxy.html"
    - title: Azure で CIFS ロックを無効にします
      url: "/task_overriding_cifs_locks.html"
    - title: 参照
      entries:
      - title: ユーザロール
        url: "/reference_user_roles.html"
      - title: 権限
        url: "/reference_permissions.html"
      - title: AWS Marketplace ページ
        url: "/reference_aws_marketplace.html"
  - title: API と自動化を活用
    entries:
    - title: API 開発者ガイド
      url: https://docs.netapp.com/us-en/occm/api.html
    - title: DevOps ツールを使用して自動化
      url: "/reference_infrastructure_as_code.html"
  - title: の問題のトラブルシューティング
    url: https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services
  - title: 関連リンク
    url: "/reference_additional_info.html"
  - title: 以前のバージョン
    url: "/reference_earlier_versions.html"
  - title: 法的通知
    url: "/reference_legal_notices.html"
