---
sidebar: sidebar 
permalink: task_planning_your_config_gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, explore, standard, premium, byol, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, Cloud Volumes ONTAP explore, Cloud Volumes ONTAP standard, Cloud Volumes ONTAP premium, Cloud Volumes ONTAP byol, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size 
summary: Cloud Volumes ONTAP を導入する場合は、ワークロード要件に一致する事前設定済みのシステムを選択するか、独自の構成を作成できます。独自の設定を選択する場合は、使用可能なオプションを理解しておく必要があります。 
---
= Google Cloud での Cloud Volumes ONTAP 構成の計画
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud に Cloud Volumes ONTAP を導入する場合は、ワークロードの要件に合わせて事前設定されたシステムを選択するか、または独自の設定を作成できます。独自の設定を選択する場合は、使用可能なオプションを理解しておく必要があります。



== ライセンスタイプの選択

Cloud Volumes ONTAP には、従量課金制とお客様所有のライセンスを使用（ BYOL ）の 2 種類の料金プランがあります。従量課金制の場合は、 Explore 、 Standard 、 Premium の 3 つのライセンスから選択できます。ライセンスごとに容量とコンピューティングのオプションが異なります。

https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_gcp_97.html["GCP の Cloud Volumes ONTAP 9.7 でサポートされている構成"^]



== ストレージの制限を理解する

Cloud Volumes ONTAP システムの未フォーマット時の容量制限は、ライセンスに関連付けられています。追加の制限は、アグリゲートとボリュームのサイズに影響します。設定を計画する際には、これらの制限に注意する必要があります。

https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_gcp_97.html["GCP の Cloud Volumes ONTAP 9.7 でのストレージの制限"]



== GCP でシステムのサイジングを行う

Cloud Volumes ONTAP システムのサイジングを行うことで、パフォーマンスと容量の要件を満たすのに役立ちます。マシンタイプ、ディスクタイプ、およびディスクサイズを選択する際には、次の点に注意してください。

マシンのタイプ:: でサポートされているマシンタイプを確認します http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Cloud Volumes ONTAP リリースノート"^] 次に、サポートされている各マシンタイプについて Google の詳細を確認します。ワークロードの要件を、マシンタイプの vCPU とメモリの数と一致させます。各 CPU コアは、ネットワークパフォーマンスを向上させることに注意してください。
+
--
詳細については、以下を参照してください。

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Google Cloud ドキュメント： N1 標準マシンタイプ"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Google Cloud のドキュメント：「 Performance"^]


--
GCP ディスクタイプ:: Cloud Volumes ONTAP 用のボリュームを作成する際には、 Cloud Volumes ONTAP がディスクに使用する基盤となるクラウドストレージを選択する必要があります。ディスクタイプには、 _Zonal SSD persistent disks _ または _Zonal standard persistent disks _ を指定できます。
+
--
SSD 永続ディスクはランダム IOPS の高い処理速度を必要とするワークロードに最適ですが、標準的な永続ディスクは経済的で、シーケンシャル読み取り / 書き込み処理にも対応できます。詳細については、を参照してください https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud のドキュメント：「ゾーン永続ディスク（標準および SSD ）」"^]。

--
GCP ディスクサイズ:: Cloud Volumes ONTAP システムを導入する際には、初期ディスクサイズを選択する必要があります。そのあと、システムの容量を Cloud Manager で管理できるようになりますが、アグリゲートを手動で作成する場合は、次の点に注意してください。
+
--
* アグリゲート内のディスクはすべて同じサイズである必要があります。
* パフォーマンスを考慮しながら、必要なスペースを判断します。
* パーシステントディスクのパフォーマンスは、システムで使用可能なディスクサイズと vCPU の数に応じて自動的に拡張されます。
+
詳細については、以下を参照してください。

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud のドキュメント：「ゾーン永続ディスク（標準および SSD ）」"^]
** https://cloud.google.com/compute/docs/disks/performance["Google Cloud のドキュメント：「 Optimizing Persistent Disk and Local SSD Performance"^]




--




== GCP ネットワーク情報ワークシート

GCP で Cloud Volumes ONTAP を導入する場合は、仮想ネットワークの詳細を指定する必要があります。ワークシートを使用して、管理者から情報を収集できます。

[cols="30,70"]
|===
| GCP 情報 | あなたの価値 


| 地域 |  


| ゾーン |  


| vPC ネットワーク |  


| サブネット |  


| ファイアウォールポリシー（独自のポリシーを使用している場合） |  
|===


== 書き込み速度の選択

Cloud Manager では、シングルノードの Cloud Volumes ONTAP システムの書き込み速度設定を選択できます。書き込み速度を選択する前に、高速書き込みを使用する場合の標準設定と高設定の違い、およびリスクと推奨事項を理解しておく必要があります。



==== 通常の書き込み速度と高速書き込み速度の差

通常の書き込み速度を選択すると、データはディスクに直接書き込まれるため、計画外のシステム停止が発生した場合にデータが失われる可能性が低くなります。

高速書き込みを選択すると、データはディスクに書き込まれる前にメモリにバッファされるため、書き込みパフォーマンスが向上します。このキャッシュにより、計画外のシステム停止が発生した場合にデータが失われる可能性があります。

計画外のシステム停止が発生した場合に失われる可能性があるデータの量は、最後の 2 つの整合ポイントの範囲です。整合ポイントとは、バッファされたデータをディスクに書き込むことです。整合ポイントは、書き込みログがいっぱいになったとき、または 10 秒後（どちらか早い方）に発生します。ただし、 AWS EBS ボリュームのパフォーマンスは、整合ポイントの処理時間に影響を与える可能性があります。



==== 高速書き込みを使用する場合

高速書き込みは、ワークロードに高速書き込みパフォーマンスが必要な場合に最適です。また、予期しないシステム停止が発生した場合にも、データ損失のリスクに耐えることができます。



==== 高速書き込みを使用する場合の推奨事項

高速書き込みを有効にする場合は、アプリケーション層で書き込み保護を確保する必要があります。



== ボリューム使用プロファイルの選択

ONTAP には、必要なストレージの合計容量を削減できるストレージ効率化機能がいくつか搭載されています。Cloud Manager でボリュームを作成する場合は、これらの機能を有効にするプロファイルを選択するか、無効にするプロファイルを選択できます。これらの機能の詳細については、使用するプロファイルを決定する際に役立ちます。

NetApp Storage Efficiency 機能には、次のようなメリットがあります。

シンプロビジョニング:: 物理ストレージプールよりも多くの論理ストレージをホストまたはユーザに提供します。ストレージスペースは、事前にストレージスペースを割り当てる代わりに、データの書き込み時に各ボリュームに動的に割り当てられます。
重複排除:: 同一のデータブロックを検索し、単一の共有ブロックへの参照に置き換えることで、効率を向上します。この手法では、同じボリュームに存在するデータの冗長ブロックを排除することで、ストレージ容量の要件を軽減します。
圧縮:: プライマリ、セカンダリ、アーカイブストレージ上のボリューム内のデータを圧縮することで、データの格納に必要な物理容量を削減します。

