---
sidebar: sidebar 
permalink: task_getting_started_gcp.html 
keywords: google cloud platform, gcp, deploy cloud manager, launch cloud manager, create cloud manager, getting started, networking, gcp networking, service account, tiering, data tiering, bucket, fabricpool, storage access key, gcp role, role, iam role, permissions, gcp permissions 
summary: Cloud Volumes ONTAP for GCP の使用を開始するには、いくつかの手順を実行します。 
---
= 『 Getting started with Cloud Volumes ONTAP for Google Cloud 』
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP for GCP の使用を開始するには、いくつかの手順を実行します。



==== コネクタを作成します

[role="quick-margin-para"]
を持っていなければ link:concept_connectors.html["コネクタ"] ただし、アカウント管理者がアカウントを作成する必要があります。 。

[role="quick-margin-para"]
最初の Cloud Volumes ONTAP 作業環境を作成する際、まだコネクタがない場合は、 Cloud Manager からコネクタの導入を求められます。



==== 構成を計画

[role="quick-margin-para"]
Cloud Manager には、ワークロードの要件に応じた事前設定パッケージが用意されています。または、独自の設定を作成することもできます。独自の設定を選択する場合は、使用可能なオプションを理解しておく必要があります。 link:task_planning_your_config_gcp.html["詳細はこちら。"]。



==== ネットワークをセットアップします

. VPC とサブネットがコネクタと Cloud Volumes ONTAP 間の接続をサポートしていることを確認します。
. ターゲット VPC からのアウトバウンドインターネットアクセスを有効にして、コネクタと Cloud Volumes ONTAP が複数のエンドポイントに接続できるようにします。
+
コネクタはアウトバウンドのインターネットアクセスがないと Cloud Volumes ONTAP を管理できないため、この手順は重要です。アウトバウンド接続を制限する必要がある場合は、のエンドポイントのリストを参照してください link:reference_networking_gcp.html["コネクタと Cloud Volumes ONTAP"]。



[role="quick-margin-para"]
link:reference_networking_gcp.html["ネットワーク要件の詳細については、こちらをご覧ください"]。



==== データ階層化用の GCP をセットアップします

[role="quick-margin-para"]
Cloud Volumes ONTAP から低コストのオブジェクトストレージ（ Google Cloud Storage バケット）にコールドデータを階層化するには、 2 つの要件を満たす必要があります。

. https://cloud.google.com/vpc/docs/configure-private-google-access["プライベート Google アクセス用の Cloud Volumes ONTAP サブネットを設定します"^]。
. https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["データ階層化用のサービスアカウントを設定します"^]：
+
** 階層化サービスアカウントに Predefined_Storage Admin_role を割り当てます。
** Connector サービスアカウントを階層化サービスアカウントに「 _ サービスアカウントユーザー _ 」として追加します。
+
ユーザロールを指定できます https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["を作成するときにウィザードの手順 3 で行います 階層化サービスのアカウント"]または。

+
Cloud Volumes ONTAP の作業環境を作成した場合、後で階層化サービスアカウントを選択する必要があります。

+
データの階層化を有効にせず、 Cloud Volumes ONTAP システムの作成時にサービスアカウントを選択した場合は、システムをオフにして、サービスアカウントを GCP コンソールから Cloud Volumes ONTAP に追加する必要があります。







==== Google Cloud API を有効にします

[role="quick-margin-para"]
https://cloud.google.com/apis/docs/getting-started#enabling_apis["プロジェクトで次の Google Cloud API を有効にします"^]。これらの API は、コネクタと Cloud Volumes ONTAP を導入するために必要です。

* Cloud Deployment Manager V2 API
* クラウドロギング API
* Cloud Resource Manager API の略
* Compute Engine API
* ID およびアクセス管理（ IAM ） API




==== Cloud Manager を使用して Cloud Volumes ONTAP を起動します

[role="quick-margin-para"]
[ 作業環境の追加 ] をクリックし、展開するシステムのタイプを選択して、ウィザードの手順を実行します。 link:task_deploying_gcp.html["詳細な手順を参照してください"]。

.関連リンク
* link:concept_evaluating.html["評価中"]
* link:task_creating_connectors_gcp.html["Cloud Manager からコネクタを作成します"]
* link:task_installing_linux.html["Linux ホストへの Connector ソフトウェアのインストール"]
* link:reference_permissions.html#what-cloud-manager-does-with-gcp-permissions["Cloud Manager が GCP 権限を使用して実行する処理"]

