---
sidebar: sidebar 
permalink: task_getting_started_aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, tiering, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create 
summary: いくつかの手順で、 Cloud Volumes ONTAP for AWS を使い始めましょう。 
---
= Cloud Volumes ONTAP for AWS での作業の開始
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
いくつかの手順で、 Cloud Volumes ONTAP for AWS を使い始めましょう。



==== コネクタを作成します

[role="quick-margin-para"]
を持っていなければ link:concept_connectors.html["コネクタ"] ただし、アカウント管理者がアカウントを作成する必要があります。 。

[role="quick-margin-para"]
最初の Cloud Volumes ONTAP 作業環境を作成する際、まだコネクタがない場合は、 Cloud Manager からコネクタの導入を求められます。



==== 構成を計画

[role="quick-margin-para"]
Cloud Manager には、ワークロードの要件に応じた事前設定パッケージが用意されています。または、独自の設定を作成することもできます。独自の設定を選択する場合は、使用可能なオプションを理解しておく必要があります。 link:task_planning_your_config.html["詳細はこちら。"]。



==== ネットワークをセットアップします

. VPC とサブネットがコネクタと Cloud Volumes ONTAP 間の接続をサポートしていることを確認します。
. ターゲット VPC からのアウトバウンドインターネットアクセスを有効にして、コネクタと Cloud Volumes ONTAP が複数のエンドポイントに接続できるようにします。
+
コネクタはアウトバウンドのインターネットアクセスがないと Cloud Volumes ONTAP を管理できないため、この手順は重要です。アウトバウンド接続を制限する必要がある場合は、のエンドポイントのリストを参照してください link:reference_networking_aws.html["コネクタと Cloud Volumes ONTAP"]。

. S3 サービスへの vPC エンドポイントをセットアップします。
+
Cloud Volumes ONTAP から低コストのオブジェクトストレージにコールドデータを階層化する場合は、 VPC エンドポイントが必要です。



[role="quick-margin-para"]
link:reference_networking_aws.html["ネットワーク要件の詳細については、こちらをご覧ください"]。



==== AWS KMS を設定します

[role="quick-margin-para"]
Cloud Volumes ONTAP で Amazon 暗号化を使用する場合は、アクティブなカスタマーマスターキー（ CMK ）が存在することを確認する必要があります。また、コネクタに「 a_key user__ 」という権限を付与する IAM ロールを追加して、各 CMK のキーポリシーを変更する必要があります。 link:task_setting_up_kms.html["詳細はこちら。"]。



==== Cloud Manager を使用して Cloud Volumes ONTAP を起動します

[role="quick-margin-para"]
[ 作業環境の追加 ] をクリックし、展開するシステムのタイプを選択して、ウィザードの手順を実行します。 link:task_deploying_otc_aws.html["詳細な手順を参照してください"]。

.関連リンク
* link:concept_evaluating.html["評価中"]
* link:task_creating_connectors_aws.html["Cloud Manager からコネクタを作成します"]
* link:task_launching_aws_mktp.html["AWS Marketplace から Connector を起動する"]
* link:task_installing_linux.html["Linux ホストへの Connector ソフトウェアのインストール"]
* link:reference_permissions.html#what-cloud-manager-does-with-aws-permissions["Cloud Manager が AWS 権限を使用して実行する処理"]

